language: python
python:
  - "3.5"
before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
  - pip install $TRAVIS_BUILD_DIR/baconian-internal

script: python baconian/test/run_all_tests.py
env: PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/baconian-internal
branches:
  only:
  - master
  - travis_ci_test