language: python
python:
  - "3.5"
dist: xenial

before_install:
  - sudo apt-get update
  - sudo apt-get install libgl1-mesa-dev
  - sudo apt-get install libpcre16-3

install:
  - pip install pip==9.0.1
  - pip install -e .

script:
  - pip install pytest pytest-cov
  - pytest --cov=baconian ./examples/ ./baconian/test/
branches:
  only:
  - master
  - travis_ci_test
  - dev_*
notifications:
  email: false

after_success:
  - codecov