language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
dist: xenial

before_install:
  -

install:
  - bash installation.sh

script:
  - pip install pytest pytest-cov
  - pytest --cov=baconian ./examples/ ./baconian/test/
branches:
  only:
  - master
  - travis_ci_test
  - dev_*
  - dev_cly_0.2
notifications:
  email: false

after_success:
  - codecov