language: python
matrix:
  include:
    - name: "Python 3.5/6/7 on Xenial Linux 16.04"
      python:
        - "3.7"
        - "3.6"
        - "3.5"
      dist: xenial
    - name: "Python 3.5/6/7 on Bionic Linux 18.04" # 3.5 may NOT be supported
      python:
        - "3.7"
        - "3.6"
        - "3.5"
      dist: bionic
    - name: "Python 3.5/6 on Trusty Linux 14.04"
      python:
        - "3.6"
        - "3.5"
      dist: trusty

before_install:
  -

install:
  - bash installation.sh

script:
  - pip install pytest pytest-cov
  - pytest --cov=baconian ./examples/ ./baconian/test/
branches:
  only:
  - master
  - travis_ci_test
  - dev_*
  - dev_cly_0.2
notifications:
  email: false

after_success:
  - codecov