language: python
python:
  - "3.5"
install:
  - pip install pip==9.0.1
  - pip install -e .

script:
  - pip install pytest pytest-cov
  - pytest --cov=baconian-project ./baconian/test/
  - pytest --cov=baconian-project ./examples/ ./baconian/test/
branches:
  only:
  - master
  - travis_ci_test
notifications:
  email: false

after_success:
  - codecov