language: python
python:
  - "3.5"
install:
  - pip install pip==9.0.1
  - pip install -e .

script:
  - echo $PYTHONPATH
  - pytest baconian/test/ -s
  - pytest examples/ -s
branches:
  only:
  - master
  - travis_ci_test
notifications:
  email: false